# Generated by Django 4.2.4 on 2023-10-26 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_article_category_tag_delete_album_delete_musician_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categ_name',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='tagName',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
